### ISSUE TITLE
Token not found for release-please GitHub Action

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/openfoodfacts-python#100]
The [release-please](https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/.github/workflows/release-please.yml) GitHub Action throws out an `Error: release-please failed: Input required and not supplied: token`.
Failed Workflow: https://github.com/openfoodfacts/openfoodfacts-python/runs/6286365168?check_suite_focus=true#step:2:12

To resolve this, a RELEASE_PLEASE_TOKEN must be added to the secrets of the openfoodfacts-python repository.

**Comment by alexgarel** [comment]
I added a personal access token from my account.
