### ISSUE TITLE
Addition to the Usage Guide

### ISSUE THREAD

**Issue by SaschaF94** [openfoodfacts/openfoodfacts-python#125]
Hello,

I am developing a smart shopping cart as part of my training to become a state-certified mechatronics technician. And for this I found your opensource data and thought that it is really nice. So I began to browse through the files but they are a bit complicated. Then I found the Usage Guide but it didnt help me really much.
So I would like to suggest some points for the Usage Guide. Some points which maybe are nomal for more experienced programmers but not for everyone.

    Something like how you can import the modul and some methods how you handle this then. And what you have to do to connect to the server(api):

    I use this one:

    api_url = "[https://world.openfoodfacts.org/api/v0/product/{}.json]".format(barcode)
    response = requests.get(api_url)
    if response.status_code == 200:
    data = response.json()
    product_name = data["product"]["product_name"]
    return product_name
    else:
    return None

    Some examples for the basic functions to get the only the different parameters of a product like the name. Yes i can look into the json data(https://world.openfoodfacts.org/api/v0/product/737628064502.json) but it is very much and how the informations are used, is not clear.

Thank you very much

Greetings

Sascha Fast

**Comment by raphael0202** [comment]
We've totally revamped the SDK, I hope the new version is easier to use!
