### ISSUE TITLE
Require a custom user agent to use the SDK

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-python#152]
### What
- Require a custom user agent to use the SDK
- Using the SDK and the API in general will remain as of today: free and accessible for everyone.
IN the same way, we don't want to implement an API key mechanism and all that kind of stuff.
- However, due to misuse of the API through various SDKs, we will now force all language clients to have a valid User Agent so that we can reach out in case of problems.
- For now, We will only require an app name for the user agent.

**Comment by butteredwaffles** [comment]
Hello @teolemon, I'm interested in contributing to this project and wanted to know if it was okay to PR for this issue!
Just to get a clearer understanding:
(1) would this would be a breaking change in the `openfoodfacts.API` constructor to force the user to provide a user agent to be passed on to the OpenFoodFacts endpoints?
or (2) non-breaking change where the user can optionally provide a user agent, but if not provided will send something like "OFF Python SDK / v0.1.12" as the agent

**Comment by teolemon** [comment]
- Thanks @butteredwaffles :-)  and welcome
- I would go for the breaking change. People hopefully have fixed dependancies, and will add the user agent when they bump the version.
