### ISSUE TITLE
Allow to specify the locale

### ISSUE THREAD

**Issue by frankrousseau** [openfoodfacts/openfoodfacts-python#16]
Results can be returned for different locales by the API. This lib in the current state doesn't allow to take advantage of it.

**Comment by Anubhav-Bhargava** [comment]
@frankrousseau By locale, do you mean getting products from different countries like

 https://fr.openfoodfacts.org/api/v0/product/737628064502.json
https://jp.openfoodfacts.org/api/v0/product/737628064502.json

**Comment by frankrousseau** [comment]
Yes this is what I meant.
