### ISSUE TITLE
Run tests on each change (continuous integration)

### ISSUE THREAD

**Issue by frankrousseau** [openfoodfacts/openfoodfacts-python#2]
Hello OFF team,

If [my PR](https://github.com/openfoodfacts/openfoodfacts-python/pull/1) is merged, this module will have unit tests. They ensure that everything work as expected for most common cases. It would be nice to run these tests everytime a change occurs in the code. 

*NB: Travis does the job well and is well integrated with Github. I suggest you this platform.*

**Comment by teolemon** [comment]
https://travis-ci.org/openfoodfacts/openfoodfacts-python

**Comment by frankrousseau** [comment]
Great thank you!

**Comment by teolemon** [comment]
Build failing

**Comment by frankrousseau** [comment]
The build is now fixed.
