### ISSUE TITLE
Inconsistency in User Agent Specification in Documentation

### ISSUE THREAD

**Issue by floodoo** [openfoodfacts/openfoodfacts-python#206]
#### What
A discrepancy has been identified in the OpenFoodFacts SDK documentation regarding the ability to set a user agent. The documentation suggests setting a user agent during API initialization, but the SDK's `API` class constructor does not support this functionality.

#### Steps to Observe the Discrepancy
1. The documentation indicates the use of a `user_agent` parameter in the `API` initialization as follows:
    ```python
    api = API(
        user_agent="<application name>",
        ...
    )
    ```
2. However, the actual `API` class constructor in the SDK lacks the `user_agent` parameter:
    ```python
    class API:
        def __init__(
            self,
            username: Optional[str] = None,
            ...
        ) -> None:
            ...
    ```

#### Expected Behavior
The SDK's documentation should accurately reflect its current functionality. If the SDK is intended to support the `user_agent` parameter, this should be correctly implemented. If not, the documentation should be updated to avoid such mentions.

#### Suggested Action
Based on this inconsistency, I recommend either:
- Updating the SDK to include a `user_agent` parameter in the `API` class constructor as per the documentation.
- Amending the documentation to remove any references to setting a user agent if this feature is not supported.

#### Platform
- OpenFoodFacts SDK and its official documentation.

#### Context of Discovery
- This issue was discovered during my first use of the OpenFoodFacts SDK, leading to initial confusion.

I look forward to a resolution that aligns the SDK with its documentation, ensuring clarity for all future users.

**Comment by Tanmay9993** [comment]
Is there a way/need to fix this issue from our side?

**Comment by namedtoaster** [comment]
I think this only happens if you install the package with pip. I had the same issue. But when I cloned the repo and installed via setup.py, that worked for me. I'm guessing the pypi package just isn't up to date?

**Comment by elebumm** [comment]
Confirming that the pypi package isn't up to date. Running:

```
pip install git+https://github.com/openfoodfacts/openfoodfacts-python#egg=openfoodfacts
```

was what fixed it for me.

**Comment by raphael0202** [comment]
I'm sorry for the response delay, I didn't see your issue.
As mentioned by @elebumm, it's now fixed on newer versions of the SDK.
