### ISSUE TITLE
Add a taxonomy retrieval module ?

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-python#212]
### What
- We have https://github.com/openfoodfacts/off-category-classification/blob/master/lib/taxonomy.py that can be useful to get information about a taxonomy as a graph.
- Should we integrate it in this SDK ?

### Part of
- #76

**Comment by raphael0202** [comment]
It's already integrated ;)
https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/openfoodfacts/taxonomy.py
