### ISSUE TITLE
Support paging

### ISSUE THREAD

**Issue by guerda** [openfoodfacts/openfoodfacts-python#22]
Currently, the library only returns 20 products, which is the first page of results provided by the API.

*Steps to reproduce*
```
>>> import openfoodfacts
>>> len(openfoodfacts.products.get_by_state("nutrition_facts_completed"))
20

```
*Expected result*
Option to page through the results. Results count should be > 62k (see https://world.openfoodfacts.org/state/nutrition-facts-completed )

**Comment by frankrousseau** [comment]
@guerda When my PR will be merged, the fix will be available.

**Comment by frankrousseau** [comment]
By the way, thank you for reporting @guerda
