### ISSUE TITLE
Add api-wrapper and client topics.

### ISSUE THREAD

**Issue by Anubhav-Bhargava** [openfoodfacts/openfoodfacts-python#33]

**Comment by frankrousseau** [comment]
Thank you @Anubhav-Bhargava for this feature request. Could you be more descriptive about what you expect?

**Comment by Anubhav-Bhargava** [comment]
@frankrousseau To increase the visibility of this repo we should add the above topics alongside python, food-products, food-classification, ingredients, allergens

**Comment by frankrousseau** [comment]
It looks like someone did it. Thanks for reporting!
