### ISSUE TITLE
Create an Open Food Facts account on Pypi.org

### ISSUE THREAD

**Issue by frankrousseau** [openfoodfacts/openfoodfacts-python#41]
Hello all,

 What about publishing this client on Pypi.org? That would allow people to install it through this command:

```
pip install openfoodfacts
```

For that we need an account on Pypi.org. @teolemon do you think you can create one for the OFF foundation?

**Comment by teolemon** [comment]
just created an account called '''openfoodfacts'''

**Comment by teolemon** [comment]
bit busy tonight because of tomorrow's general assembly, but ping me for further instructions

**Comment by frankrousseau** [comment]
Ok, I just need the password. If you can email it to me, I will publish the client. If you want to do it by yourself, I will send you detailed information.

**Comment by frankrousseau** [comment]
In fact you can do it easily:

```
pip install wheel
pip setup.py bdist_wheel

pip install twine
twine upload dist/zou-0.5.5-py2.py3-none-any.whl
```

**Comment by frankrousseau** [comment]
I prefer to let someone of the core team to create the openfoodfacts account.

I think a conda package would be good too.

**Comment by teolemon** [comment]
I have created an account @frankrousseau

**Comment by frankrousseau** [comment]
Can you give me access or run the publcation procedure?

**Comment by astagi** [comment]
Is there any update on this issue?

**Comment by frankrousseau** [comment]
I still have no access to openfoodfacts account on Pypi.

**Comment by astagi** [comment]
Yeah looks like @teolemon opened an account 2 years ago :) Do you know if Robotoff is released under **openfoodfacts** account (https://pypi.org/user/raphael0202/)?

**Comment by teolemon** [comment]
I've just created a token. @frankrousseau @astagi can you ping in private on Slack ?

**Comment by astagi** [comment]
@frankrousseau the discussion is continuing on slack at the moment :) token is ready, we're talking about who should upload the package on pypi. If it's ok for you I can take care of this task preparing required scripts, files and tags for pypi.

**Comment by frankrousseau** [comment]
Yes that would be great. I'm super busy at the moment and don't know how to connect to the Slack you mention.

**Comment by astagi** [comment]
No problem, I'll take care of this task :)

**Comment by astagi** [comment]
@teolemon let's talk about package upload on slack, scripts and required files are ready on master.

**Comment by astagi** [comment]
Fixed by #64 https://pypi.org/project/openfoodfacts/

**Comment by frankrousseau** [comment]
Awesome!

**Comment by frankrousseau** [comment]
Thank you @astagi!
