### ISSUE TITLE
README.md too long

### ISSUE THREAD

**Issue by Anubhav-Bhargava** [openfoodfacts/openfoodfacts-python#47]
**Problem**

With the recent advancements in the functionality of Python-Client,  the readme.md file has become too long. Making it difficult to search for the needed functionality

**Solution**

Setup a wiki like (https://en.wiki.openfoodfacts.org/API) or a blog like (https://keras.io/)

**Comment by Anubhav-Bhargava** [comment]
@teolemon @frankrousseau  What do you think?

**Comment by enioluwa23** [comment]
Can I work on this? I'm familiar with the features and can create the usage guide that will be linked from the readme.

**Comment by Anubhav-Bhargava** [comment]
@enioluwa23 Sure!

**Comment by enioluwa23** [comment]
#48 Done! Review when you have the chance.
