### ISSUE TITLE
Make it possible to create an Open Beauty Facts variant

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-python#5]

**Comment by Anubhav-Bhargava** [comment]
@frankrousseau  For this should we make a separate file, that will contain all the functions related to OBF?

and the API is also currently experimental https://en.wiki.openfoodfacts.org/API/OpenBeautyFacts

**Comment by frankrousseau** [comment]
Yes it seems a good idea. 

A `build_url` function will be probably required too.
