### ISSUE TITLE
Package for Conda

### ISSUE THREAD

**Issue by ivanhercaz** [openfoodfacts/openfoodfacts-python#54]
I saw #41 is pending yet, but I think it might be interesting to have this package in Conda too, because it is used quite a lot, especially in the scientific-linked open data environment. Building a conda doesn't seem very hard. I have never build one, but I could try it. There are many [documentation](https://conda.io/docs/user-guide/tasks/build-packages/index.html) about it.

What do you think?

**Comment by aadarsh-ram** [comment]
@teolemon I'll be working on this issue. I have issued a PR for it as well.
