### ISSUE TITLE
Unable to find my packager code with get_packaging_codes()

### ISSUE THREAD

**Issue by A1CY0N** [openfoodfacts/openfoodfacts-python#66]
Some packaging code existing on the web interface is not returned by the `get_packaging_codes()` function which obviously uses this [url](http://world.openfoodfacts.org/packager-codes.json).

An example here: https://world.openfoodfacts.org/product/6842420174016/chocolat. The packaging code is `EMB 07113Y` but it does not appear in the list of packaging codes.

Moreover, I have the impression that the terms `packaging_code`, `packager_code` and `emb_code` that we find indistinctly in the doc design the same thing.

**Comment by A1CY0N** [comment]
As mentioned here openfoodfacts/openfoodfacts-server#4405, it would be interesting to implement a filter on the get_packaging_codes() function to reduce results and avoid limitations on the 10000 results.

**Comment by astagi** [comment]
@A1CY0N sorry for the late reply. Now you can accomplish your filtering using

```python
codes = openfoodfacts.facets.get_packaging_codes(
    parameters={'filter': 'emb'}
)
```

For now the fix is on master, let me know if it works for you!
