### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-python#77]
### What

- [ ] Tests are failing

Run # stop the build if there are Python syntax errors or undefined names
./draft.py:61:6: E999 SyntaxError: invalid syntax
with # with_additives
     ^
./openfoodfacts/__init__.py:74:13: F821 undefined name 'products'
    setattr(products, func.__name__, func)
            ^
./openfoodfacts/__init__.py:89:13: F821 undefined name 'products'
    setattr(products, func_all.__name__, func_all)
            ^
1     E999 SyntaxError: invalid syntax
2     F821 undefined name 'products'
3
Error: Process completed with exit code 1.

### Part of
- #76

**Comment by aadarsh-ram** [comment]
Hi @teolemon,
Regarding the F821 error, it seems there's a [bug](https://stackoverflow.com/questions/67547135/why-does-flake8-give-the-warning-f821-undefined-name-match-when-using-match) in pyflakes.
The E999 error is part of the [draft.py](https://github.com/openfoodfacts/openfoodfacts-python/blob/develop/draft.py) file. I don't think it is being used anywhere inside the whole package. So, I think it can be safely removed.

Please do share your feedback regarding this.

**Comment by aadarsh-ram** [comment]
@teolemon This issue has been resolved with PR #88
